### PR TITLE
Fix building on kernel >= 6.12

### PR DESCRIPTION
**Pull request by LivingWithHippos**
`asm/unaligned.h` has been renamed to `linux/unaligned.h` in kernel 6.12 (debian's default)

I was able to build, haven't tested if it works yet

### CODE REVIEW

**Comment by KSMaan45** [comment]
hey are you able to build on kernel 6.15? i'm having following error for rt_config.h which hasn't move but unable to find

make -C /lib/modules/6.15.7-arch1-1/build M=/home/maan/Desktop/mt7601u-ap/os/linux modules
make[1]: Entering directory '/usr/lib/modules/6.15.7-arch1-1/build'
make[2]: Entering directory '/home/maan/Desktop/mt7601u-ap/os/linux'
  CC [M]  ../../os/linux/rt_profile.o
../../os/linux/rt_profile.c:26:10: fatal error: rt_config.h: No such file or directory
   26 | #include "rt_config.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [/usr/lib/modules/6.15.7-arch1-1/build/scripts/Makefile.build:203: ../../os/linux/rt_profile.o] Error 1
make[3]: *** [/usr/lib/modules/6.15.7-arch1-1/build/Makefile:2003: .] Error 2
make[2]: *** [/usr/lib/modules/6.15.7-arch1-1/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/home/maan/Desktop/mt7601u-ap/os/linux'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.15.7-arch1-1/build'
make: *** [Makefile:73: LINUX] Error 2

**Comment by marcgm95** [comment]
The rename of "asm/unaligned.h" to "linux/unaligned.h" works and the installation is complete.
